<?php
/**
 * Launchpad Blocks — theme bootstrap.
 *
 * theme.json remains the single source of truth for tokens (palette, type scale, spacing, radius) and
 * per-variation styling. Two things it CANNOT express are enqueued here:
 *
 *  1. The `.lp-*` SECTION LAYOUTS. The pages the control plane composes are core Gutenberg blocks
 *     tagged with layout classes (`lp-hero`, `lp-services-grid`, `lp-card`, `lp-proof-grid`, `lp-cta`,
 *     …). theme.json styles block TYPES, not arbitrary classes, so the grid/card/hero arrangements
 *     live in assets/theme.css — keyed to those classes with real specificity, so they win over the
 *     zero-specificity `:where()` layout rules WordPress injects from theme.json.
 *
 *  2. The bundled heading @font-face rules for EVERY variation (Archivo / Manrope / Bricolage). WP
 *     only prints font-faces for the *active* variation's families; declaring them all here means the
 *     heading webfont always loads, so switching a style variation can never fall back to system-ui.
 *
 * A block theme does not auto-enqueue any front-end stylesheet, so this hook is the delivery path.
 *
 * @package LaunchpadBlocks
 */

if (! defined('ABSPATH')) {
    exit;
}

add_action('wp_enqueue_scripts', function (): void {
    $theme = wp_get_theme();
    $version = (string) $theme->get('Version');
    $dir = get_stylesheet_directory_uri();

    // Serve the minified build (assets/theme.min.css, regenerated by tools/minify-css.php) — a third
    // smaller and a single request. theme.css stays the readable source of truth; fall back to it only
    // if the minified file is somehow missing.
    $cssFile = file_exists(get_stylesheet_directory().'/assets/theme.min.css') ? 'theme.min.css' : 'theme.css';
    wp_enqueue_style('launchpad-blocks', $dir.'/assets/'.$cssFile, [], $version);
});

/**
 * "Areas we serve" interactive map — LAZY loaded. Leaflet (~147KB JS + its CSS) is the heaviest thing
 * on a page that has one, and the map lives below the fold, so instead of enqueuing it on load we print
 * a tiny loader that fetches Leaflet + area-map only when the map scrolls near the viewport
 * (IntersectionObserver, 300px margin). This cuts the request count and initial page weight for every
 * map page; pages without the `_lp_area_map` meta load nothing (the section shows its text fallback).
 *
 * The companion plugin prints the geometry as `window.lpAreaMap` at wp_footer priority 1; this loader
 * runs later (priority 20) and injects area-map.js, which self-inits (readyState-aware) once Leaflet is
 * present. Minified builds are served when available (area-map.min.js / leaflet.min.css).
 */
add_action('wp_footer', function (): void {
    if (! (is_singular() && get_post_meta(get_queried_object_id(), '_lp_area_map', true))) {
        return;
    }

    $path = get_stylesheet_directory();
    $uri = get_stylesheet_directory_uri();
    $version = (string) wp_get_theme()->get('Version');

    $leafletCss = is_file($path.'/assets/vendor/leaflet/leaflet.min.css') ? 'leaflet.min.css' : 'leaflet.css';
    $areaMap = is_file($path.'/assets/area-map.min.js') ? 'area-map.min.js' : 'area-map.js';

    $urls = wp_json_encode([
        'css' => esc_url_raw($uri.'/assets/vendor/leaflet/'.$leafletCss.'?ver=1.9.4'),
        'leaflet' => esc_url_raw($uri.'/assets/vendor/leaflet/leaflet.js?ver=1.9.4'),
        'map' => esc_url_raw($uri.'/assets/'.$areaMap.'?ver='.$version),
    ]);

    // wp_json_encode escapes "</" and "/", so the URLs can't break out of the <script>.
    echo '<script id="lp-area-map-loader">(function(){var el=document.querySelector(".lp-areas-map");if(!el)return;'
        .'var u='.$urls.',done=false;function load(){if(done)return;done=true;'
        .'var l=document.createElement("link");l.rel="stylesheet";l.href=u.css;document.head.appendChild(l);'
        .'var s=document.createElement("script");s.src=u.leaflet;s.onload=function(){'
        .'var m=document.createElement("script");m.src=u.map;document.body.appendChild(m);};document.body.appendChild(s);}'
        ."if('IntersectionObserver' in window){var io=new IntersectionObserver(function(es){"
        .'es.forEach(function(e){if(e.isIntersecting){load();io.disconnect();}});},{rootMargin:"300px"});io.observe(el);}'
        ."else{load();}})();</script>\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}, 20);
