<?php
/**
 * Launchpad Blocks — theme bootstrap.
 *
 * theme.json remains the single source of truth for tokens (palette, type scale, spacing, radius) and
 * per-variation styling. Two things it CANNOT express are enqueued here:
 *
 *  1. The `.lp-*` SECTION LAYOUTS. The pages the control plane composes are core Gutenberg blocks
 *     tagged with layout classes (`lp-hero`, `lp-services-grid`, `lp-card`, `lp-proof-grid`, `lp-cta`,
 *     …). theme.json styles block TYPES, not arbitrary classes, so the grid/card/hero arrangements
 *     live in assets/theme.css — keyed to those classes with real specificity, so they win over the
 *     zero-specificity `:where()` layout rules WordPress injects from theme.json.
 *
 *  2. The bundled heading @font-face rules for EVERY variation (Archivo / Manrope / Bricolage). WP
 *     only prints font-faces for the *active* variation's families; declaring them all here means the
 *     heading webfont always loads, so switching a style variation can never fall back to system-ui.
 *
 * A block theme does not auto-enqueue any front-end stylesheet, so this hook is the delivery path.
 *
 * @package LaunchpadBlocks
 */

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Featured-image (post-thumbnail) support. Block themes get this implicitly, but declaring it
 * explicitly guarantees `set_post_thumbnail()` (the companion plugin sideloads the blog hero and sets
 * it as the thumbnail) and the `wp:post-featured-image` block in single/index render the hero — without
 * it a blog post shows title + body but no image.
 */
add_action('after_setup_theme', function (): void {
    add_theme_support('post-thumbnails');
});

add_action('wp_enqueue_scripts', function (): void {
    $theme = wp_get_theme();
    $version = (string) $theme->get('Version');
    $dir = get_stylesheet_directory_uri();

    // Serve the minified build (assets/theme.min.css, regenerated by tools/minify-css.php) — a third
    // smaller and a single request. theme.css stays the readable source of truth; fall back to it only
    // if the minified file is somehow missing.
    $cssFile = file_exists(get_stylesheet_directory().'/assets/theme.min.css') ? 'theme.min.css' : 'theme.css';
    wp_enqueue_style('launchpad-blocks', $dir.'/assets/'.$cssFile, [], $version);

    // Grouped-nav interaction — makes the header services menu click-to-open (hover fails on touch;
    // mobile-heavy audience), keyboard + ARIA, Escape / outside-click to close. Tiny, no deps, in the
    // footer, and pure progressive enhancement over the CSS hover/focus fallback. Minified build preferred.
    $navJs = file_exists(get_stylesheet_directory().'/assets/nav.min.js') ? 'nav.min.js' : 'nav.js';
    wp_enqueue_script('launchpad-nav', $dir.'/assets/'.$navJs, [], $version, true);
});

/**
 * "Areas we serve" map — nothing to load.
 *
 * It was Leaflet (~147KB) plus a stylesheet plus CARTO's basemap tiles, lazily fetched when the map
 * scrolled into view. CARTO now requires an API key for those tiles and stamped "API KEY REQUIRED"
 * across live customer maps, so the companion plugin draws the map server-side as inline SVG from the
 * same geometry instead — no script, no stylesheet, no tile CDN, no key. The loader is gone with it.
 */
